version: "3.7"
networks:
  karura:
    ipam:
     config:
      - subnet: 172.20.0.0/24
services:
  relaychain-alice:
    networks:
      karura:
        ipv4_address: 172.20.0.2
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - relaychain-alice:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --no-beefy
      - --force-authoring
    environment:
      RUST_LOG: babe=debug
    ulimits:
      &a1
      nofile:
        soft: 65536
        hard: 65536

  relaychain-bob:
    networks:
      karura:
        ipv4_address: 172.20.0.3
    ports:
      - 9945:9944
      - 9934:9933
      - 30334:30333
    volumes:
      - relaychain-bob:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      - --rpc-methods=unsafe
      - --no-beefy
    environment:
      RUST_LOG: parachain::candidate-backing=trace
    ulimits: *a1

  parachain-2000-0:
    networks:
      karura:
        ipv4_address: 172.20.0.4
    ports:
      - 19946:9944
      - 19935:9933
      - 31335:30333
    expose:
      - 19946
    volumes:
      - parachain-2000-0:/acala/data
    build:
      context: .
      dockerfile: parachain-2000.Dockerfile
    command:
      - --base-path=/acala/data
      - --chain=/app/karura-dev-2000.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
      - --alice
      - --node-key=940f6e098f7ffa7e1c6589296ae1742cd777687cd2f18b3bf5600bc0805e307b
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --no-beefy
      - --name=relaychain-alice
    environment:
      RUST_LOG: aura=debug
    ulimits: *a1

  # sidecar:
  #   networks:
  #     karura:
  #       ipv4_address: 172.20.0.5
  #   image: docker.io/parity/substrate-api-sidecar:v11.3.5
  #   read_only: true
  #   ports:
  #     - "8081:8081"
  #   environment:
  #       SAS_SUBSTRATE_WS_URL: ws://172.20.0.4:19946
  #       SAS_EXPRESS_BIND_HOST: 0.0.0.0
  #       SAS_EXPRESS_PORT: 8081
volumes:
  ? relaychain-alice
  ? relaychain-bob
  ? parachain-2000-0